# === modeling/features.py ===
custom_feature_names = {
    'Sex_2': "Female",
    'TB_type_2': 'Relapse',
    'TB_type_3': 'TB Return from Default',
    'TB_type_4': 'Treatment Failure',
    'TB_type_5': 'Chronic TB',
    'TB_type_6': 'Initiated Treatment Abroad',
    'TB_type_21': 'SSM Negative Relapse',
    'TB_type_22': 'Extrapulmonary Relapse',
    'Occupation_1': 'Employed',
    'Occupation_2': 'Disabled',
    'Occupation_3': 'Retired',
    'Occupation_4': 'Student',
    'Occupation_5': 'Unemployed',
    'Education_1': 'Primary Education',
    'Education_2': 'Secondary Education',
    'Education_3': 'Specialized Secondary Education',
    'Education_4': 'Higher Education',
    'Education_5': 'No Education',
    'Living_condition_0': 'Unsatisfactory Living Conditions',
    'Living_condition_1': 'Satisfactory Living Conditions',
    'Outside_moldova_1': 'Resided outside of Moldova',
    'Urban_0': 'Rural Area',
    'Urban_1': 'Urban Area',
    'Homeless_1': 'Homeless',
    'Money_assistance_1': 'Receives Monetary Assistance',
    'Incarceration_1': 'Previously Incarcerated',
    'Microscopy_1': 'Positive Microscopy',
    'prevalence_0': 'Reside in District with Prevalence < 10%',
    'prevalence_1': 'Reside in District with Prevalence < 20% and > 10%',
    'prevalence_2': 'Reside in District with Prevalence >20%'
}
