# === modeling/features.py ===
custom_feature_names = {
    'Sex_1': 'Sex: Male',
    'Sex_2': 'Sex: Female',
    'Family_size': 'Family size',
    'TB_type_2': 'TB Type: Relapse',
    'TB_type_3': 'TB Type: Return from default',
    'TB_type_4': 'TB Type: Treatment failure',
    'TB_type_5': 'TB Type: Chronic TB',
    'TB_type_6': 'TB Type: Initiated treatment abroad',
    'TB_type_21': 'TB Type: SSM Negative relapse',
    'TB_type_22': 'TB Type: Extrapulmonary relapse',
    'Occupation_1': 'Occupation: Employed',
    'Occupation_2': 'Occupation: Disabled',
    'Occupation_3': 'Occupation: Retired',
    'Occupation_4': 'Occupation: Student',
    'Occupation_5': 'Occupation: Unemployed',
    'Education_1': 'Education: Primary education',
    'Education_2': 'Education: Secondary education',
    'Education_3': 'Education: Specialized secondary education',
    'Education_4': 'Education: Higher education',
    'Education_5': 'Education: No Education',
    'Education_missing': 'Education: Education missing',
    'Living_condition_0': 'Living Condition: Unsatisfactory living condition',
    'Living_condition_1': 'Living Condition: Satisfactory living condition',
    'Outside_moldova_0': 'Outside Moldova: Did not resided outside of Moldova',
    'Outside_moldova_1': 'Outside Moldova: Resided outside of Moldova',
    'Urban_0': 'Urban: Rural area',
    'Urban_1': 'Urban: Urban area',
    'Homeless_0': 'Homeless: Not homeless',
    'Homeless_1': 'Homeless: Homeless',
    'Homeless_missing': 'Homeless: Homeless missing',
    'Money_assistance_0': 'Money assistance: Does not receive monetary assistance',
    'Money_assistance_1': 'Money assistance: Receives monetary assistance',
    'Incarceration_0': 'Incarceration: Not previously incarcerated',
    'Incarceration_1': 'Incarceration: Previously incarcerated',
    'Incarceration_missing': 'Incarceration: Incarceration missing ',
    'Microscopy_1': 'Positive Microscopy',
    'prevalence_0': 'Prevalence: Reside in District with Prevalence < 10%',
    'prevalence_1': 'Prevalence: Reside in District with Prevalence < 20% and > 10%',
    'prevalence_2': 'Prevalence: Reside in District with Prevalence >20%',
    'prevalence_NA': 'Prevalence: Missing'
}
